### ISSUE TITLE
北極の海氷分布を描く

### ISSUE THREAD

**Issue by mokkei1978** [mri-ocean/OMIPj#8]
Phase 1 のゴール。

**Comment by mokkei1978** [comment]
豊田さんの担当としました。 @ttoyoda-mri 
川崎さんによるSSTと合わせるために、2000年の作図をお願いします。

気象研内ではOMIPデータは front:/storage1/M201/htsujino/OMIP に置いてあります。
また、サンプルコードを動かすためのサンプルデータについては、omipjリポジトリのdoc/install.mdを参照してください。

**Comment by ttoyoda-mri** [comment]
![sic_Mar2000_MIROC-COCO4 9](https://user-images.githubusercontent.com/72907177/103738580-91888a00-5037-11eb-91db-bc8c7f495d60.png)
![sic_Mar2000_MRI COM](https://user-images.githubusercontent.com/72907177/103738592-99e0c500-5037-11eb-910f-bb59197493ee.png)

**Comment by ttoyoda-mri** [comment]
![sic_Sep2000_MIROC-COCO4 9](https://user-images.githubusercontent.com/72907177/103738605-a402c380-5037-11eb-9194-8677a84ef018.png)
![sic_Sep2000_MRI COM](https://user-images.githubusercontent.com/72907177/103738608-a533f080-5037-11eb-89a7-564ff2746a6a.png)

**Comment by ttoyoda-mri** [comment]
2000年の3月と9月の比較を描画しました。

**Comment by mokkei1978** [comment]
ありがとうございます！大変お疲れさまでした。後はこちらで整理しておきます。

**Comment by mokkei1978** [comment]
豊田さん作成のコードを加えました。本件は終了とします。

- anl/omip/phase1/siconc_polar.py
- anl/omip/sample/siconc_polar.py
